### ISSUE TITLE
fbx support

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [zeganstyl/thelema-engine#3]
Any plans for fbx support?

**Comment by zeganstyl** [comment]
For now I haven't any plans for FBX support.
I only focused only on glTF, because it supports most of things that needed for modern 3D graphics. And glTF specification is open and clear.
It is easier to convert from FBX to glTF, rather than implement FBX support.

I think it is better to [implement Assimp support](https://lwjglgamedev.gitbooks.io/3d-game-development-with-lwjgl/content/chapter27/chapter27.html) It will be cool if someone will implement this. Or maybe I will try to implement it in the future, but I cannot promise.

**Comment by dmitrykolesnikovich** [comment]
is this tool good enough? https://github.com/facebookincubator/FBX2glTF
or you have another tool to suggest?

**Comment by dmitrykolesnikovich** [comment]
Maybe i will try to port this from cpp to kotlin https://github.com/jskorepa/fbx

It's always nice to make "complete" solution

**Comment by zeganstyl** [comment]
> is this tool good enough? https://github.com/facebookincubator/FBX2glTF or you have another tool to suggest?

Previously I used Blender for this purpose. Tried FBX2glTF with Mixamo characters, I think it is good.

**Comment by dmitrykolesnikovich** [comment]
By the way I found workable FBX support using Java https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/file/FbxReader.java

I think I will use this for my engine.
